version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Evita que o node_modules seja recriado dentro do container
    environment:
      - NODE_ENV=development
